export interface ToolField{key:string;label:string;type:'text'|'password'|'select';placeholder:string;options?:string[]}
export interface ToolInfo{id:string;name:string;shortName:string;vendor:string;category:string;categoryLabel:string;color:string;icon:string;fields:ToolField[];docs:string;description:string}
export const TOOLS:ToolInfo[]=[
{id:'defender',name:'Microsoft Defender',shortName:'Defender',vendor:'Microsoft',category:'xdr',categoryLabel:'XDR / EDR',color:'#60a5fa',icon:'🛡',fields:[{key:'AZURE_TENANT_ID',label:'Tenant ID',type:'text',placeholder:'Tenant ID'},{key:'AZURE_CLIENT_ID',label:'Client ID',type:'text',placeholder:'Client ID'},{key:'AZURE_CLIENT_SECRET',label:'Client Secret',type:'password',placeholder:'Secret'}],docs:'Azure Portal → App Registrations → API Permissions',description:'MDE + M365 Defender XDR'},
{id:'crowdstrike',name:'CrowdStrike Falcon',shortName:'CrowdStrike',vendor:'CrowdStrike',category:'edr',categoryLabel:'EDR',color:'#ef4444',icon:'🦅',fields:[{key:'CS_CLIENT_ID',label:'Client ID',type:'text',placeholder:'OAuth2 Client ID'},{key:'CS_CLIENT_SECRET',label:'Client Secret',type:'password',placeholder:'OAuth2 Secret'},{key:'CS_BASE_URL',label:'Region',type:'select',placeholder:'Region',options:['https://api.crowdstrike.com','https://api.eu-1.crowdstrike.com','https://api.us-2.crowdstrike.com']}],docs:'Falcon Console → API Clients & Keys',description:'Falcon detections and host data'},
{id:'sentinelone',name:'SentinelOne',shortName:'S1',vendor:'SentinelOne',category:'edr',categoryLabel:'EDR',color:'#a855f7',icon:'🔮',fields:[{key:'S1_API_TOKEN',label:'API Token',type:'password',placeholder:'Console API token'},{key:'S1_BASE_URL',label:'Console URL',type:'text',placeholder:'https://usea1.sentinelone.net'}],docs:'S1 Console → Settings → API Token',description:'Threats, agents, endpoint health'},
{id:'cortex',name:'Palo Alto Cortex XDR',shortName:'Cortex',vendor:'Palo Alto',category:'xdr',categoryLabel:'XDR',color:'#f97316',icon:'🔥',fields:[{key:'CORTEX_API_KEY',label:'API Key',type:'password',placeholder:'Advanced API key'},{key:'CORTEX_API_KEY_ID',label:'Key ID',type:'text',placeholder:'Key ID'},{key:'CORTEX_FQDN',label:'FQDN',type:'text',placeholder:'api-yourorg.xdr.paloaltonetworks.com'}],docs:'Cortex XDR → Settings → API Keys',description:'XDR incidents, alerts, endpoints'},
{id:'carbonblack',name:'Carbon Black',shortName:'CB',vendor:'Broadcom',category:'edr',categoryLabel:'EDR',color:'#22c55e',icon:'🌿',fields:[{key:'CB_API_ID',label:'API ID',type:'text',placeholder:'API ID'},{key:'CB_API_KEY',label:'API Key',type:'password',placeholder:'API secret'},{key:'CB_ORG_KEY',label:'Org Key',type:'text',placeholder:'Org key'},{key:'CB_BASE_URL',label:'Base URL',type:'text',placeholder:'https://defense.conferdeploy.net'}],docs:'CB Cloud → Settings → API Access',description:'Alerts, watchlists, devices'},
{id:'taegis',name:'Secureworks Taegis',shortName:'Taegis',vendor:'Secureworks',category:'xdr',categoryLabel:'XDR',color:'#c084fc',icon:'🎯',fields:[{key:'TAEGIS_CLIENT_ID',label:'Client ID',type:'text',placeholder:'Client ID'},{key:'TAEGIS_CLIENT_SECRET',label:'Client Secret',type:'password',placeholder:'Secret'},{key:'TAEGIS_REGION',label:'Region',type:'select',placeholder:'Region',options:['us','eu']}],docs:'Taegis Console → API Clients',description:'Alerts, investigations, detections'},
{id:'darktrace',name:'Darktrace',shortName:'Darktrace',vendor:'Darktrace',category:'ndr',categoryLabel:'NDR',color:'#f59e0b',icon:'🌐',fields:[{key:'DT_BASE_URL',label:'Appliance URL',type:'text',placeholder:'https://darktrace.yourorg.com'},{key:'DT_PUB_TOKEN',label:'Public Token',type:'text',placeholder:'Public token'},{key:'DT_PRIV_TOKEN',label:'Private Token',type:'password',placeholder:'Private token'}],docs:'Darktrace → Admin → API Settings',description:'Model breaches, anomalies, AI Analyst'},
{id:'tenable',name:'Tenable.io',shortName:'Tenable',vendor:'Tenable',category:'vuln',categoryLabel:'Vulnerability',color:'#5eead4',icon:'🔓',fields:[{key:'TENABLE_ACCESS_KEY',label:'Access Key',type:'password',placeholder:'Access key'},{key:'TENABLE_SECRET_KEY',label:'Secret Key',type:'password',placeholder:'Secret key'}],docs:'Tenable.io → Settings → API Keys',description:'Vulns, assets, scan results'},
{id:'qualys',name:'Qualys VMDR',shortName:'Qualys',vendor:'Qualys',category:'vuln',categoryLabel:'Vulnerability',color:'#f472b6',icon:'🔍',fields:[{key:'QUALYS_USERNAME',label:'Username',type:'text',placeholder:'Username'},{key:'QUALYS_PASSWORD',label:'Password',type:'password',placeholder:'Password'},{key:'QUALYS_BASE_URL',label:'Platform',type:'select',placeholder:'Platform',options:['https://qualysapi.qualys.com','https://qualysapi.qg2.apps.qualys.com','https://qualysapi.qualys.eu']}],docs:'Qualys → User Management → API Access',description:'VMDR vulnerability data'},
{id:'rapid7',name:'Rapid7 InsightVM',shortName:'Rapid7',vendor:'Rapid7',category:'vuln',categoryLabel:'Vulnerability',color:'#fb923c',icon:'⚡',fields:[{key:'R7_API_KEY',label:'API Key',type:'password',placeholder:'API key'},{key:'R7_BASE_URL',label:'Console URL',type:'text',placeholder:'https://insightvm:3780'}],docs:'InsightVM → Administration → API',description:'Vulns, risk scores, remediation'},
{id:'zscaler_zia',name:'Zscaler ZIA',shortName:'ZIA',vendor:'Zscaler',category:'swg',categoryLabel:'Web Gateway',color:'#fcd34d',icon:'☁',fields:[{key:'ZIA_BASE_URL',label:'API URL',type:'text',placeholder:'https://zsapi.zscalerthree.net'},{key:'ZIA_API_KEY',label:'API Key',type:'password',placeholder:'API key'},{key:'ZIA_USERNAME',label:'Username',type:'text',placeholder:'Admin user'},{key:'ZIA_PASSWORD',label:'Password',type:'password',placeholder:'Password'}],docs:'ZIA Admin → API Key Management',description:'Web security, blocked threats, DLP'},
{id:'zscaler_zpa',name:'Zscaler ZPA',shortName:'ZPA',vendor:'Zscaler',category:'ztna',categoryLabel:'ZTNA',color:'#fcd34d',icon:'🔒',fields:[{key:'ZPA_CLIENT_ID',label:'Client ID',type:'text',placeholder:'Client ID'},{key:'ZPA_CLIENT_SECRET',label:'Client Secret',type:'password',placeholder:'Secret'},{key:'ZPA_CUSTOMER_ID',label:'Customer ID',type:'text',placeholder:'Customer ID'}],docs:'ZPA Admin → API Keys',description:'Private access, connectors, posture'},
{id:'recordedfuture',name:'Recorded Future',shortName:'RecFuture',vendor:'Recorded Future',category:'ti',categoryLabel:'Threat Intel',color:'#f87171',icon:'📡',fields:[{key:'RF_API_TOKEN',label:'API Token',type:'password',placeholder:'API token'}],docs:'RF → User Settings → API Access',description:'Threat intel, risk scores, IOCs'},
{id:'splunk',name:'Splunk',shortName:'Splunk',vendor:'Cisco',category:'siem',categoryLabel:'SIEM',color:'#4ade80',icon:'📊',fields:[{key:'SPLUNK_BASE_URL',label:'Splunk URL',type:'text',placeholder:'https://splunk:8089'},{key:'SPLUNK_TOKEN',label:'Token',type:'password',placeholder:'Auth token'}],docs:'Splunk → Settings → Tokens',description:'Notable events, saved searches'},
{id:'sentinel',name:'Microsoft Sentinel',shortName:'Sentinel',vendor:'Microsoft',category:'siem',categoryLabel:'SIEM',color:'#38bdf8',icon:'🏰',fields:[{key:'SENTINEL_WORKSPACE_ID',label:'Workspace ID',type:'text',placeholder:'Workspace ID'},{key:'SENTINEL_TENANT_ID',label:'Tenant ID',type:'text',placeholder:'Tenant ID'},{key:'SENTINEL_CLIENT_ID',label:'Client ID',type:'text',placeholder:'Client ID'},{key:'SENTINEL_CLIENT_SECRET',label:'Secret',type:'password',placeholder:'Secret'}],docs:'Azure → Sentinel → API',description:'Incidents, analytics, hunting'},
{id:'wiz',name:'Wiz',shortName:'Wiz',vendor:'Wiz',category:'cloud',categoryLabel:'Cloud Security',color:'#818cf8',icon:'🧙',fields:[{key:'WIZ_CLIENT_ID',label:'Client ID',type:'text',placeholder:'Client ID'},{key:'WIZ_CLIENT_SECRET',label:'Secret',type:'password',placeholder:'Secret'},{key:'WIZ_API_URL',label:'API URL',type:'text',placeholder:'https://api.app.wiz.io/graphql'}],docs:'Wiz → Settings → Service Accounts',description:'Cloud misconfigs, vulns, attack paths'},
{id:'proofpoint',name:'Proofpoint TAP',shortName:'Proofpoint',vendor:'Proofpoint',category:'email',categoryLabel:'Email Security',color:'#e879f9',icon:'📧',fields:[{key:'PP_SERVICE_PRINCIPAL',label:'Principal',type:'text',placeholder:'Service principal'},{key:'PP_SECRET',label:'Secret',type:'password',placeholder:'Secret'}],docs:'Proofpoint → TAP API Credentials',description:'Targeted attacks, blocked messages'},
];
