import { NextRequest, NextResponse } from 'next/server';
import { redisGet, KEYS } from '@/lib/redis';
import { sendEmail } from '@/lib/email';
import { checkRateLimit } from '@/lib/ratelimit';

function requireAdmin(req: NextRequest) {
  return req.headers.get('x-is-admin') === 'true';
}

// On-demand client report: generates exec summary and emails it to the client
export async function POST(req: NextRequest) {
  // Rate limiting — 60 req/min per user
  const _rlId = req.headers.get('x-user-id') || req.headers.get('x-forwarded-for') || 'anon';
  const _rl = await checkRateLimit(`api:${_rlId}:${req.nextUrl.pathname}`, 60, 60);
  if (!_rl.ok) return NextResponse.json({ error: 'Rate limit exceeded' }, { status: 429 });

  if (!requireAdmin(req)) {
    return NextResponse.json({ error: 'Admin only' }, { status: 403 });
  }

  try {
    const body = await req.json() as {
      clientTenantId: string;
      clientName: string;
      recipientEmail: string;
    };

    if (!body.clientTenantId || !body.recipientEmail) {
      return NextResponse.json({ ok: false, error: 'clientTenantId and recipientEmail required' }, { status: 400 });
    }

    // Fetch last exec summary for this client tenant if available
    const adminTenantId = req.headers.get('x-tenant-id') || 'global';
    const summaryRaw = await redisGet(`wt:${body.clientTenantId}:exec_summary`);
    const summary = summaryRaw ? JSON.parse(summaryRaw) : null;

    // Generate the report email
    const html = `
<!DOCTYPE html>
<html>
<head><style>body{font-family:Inter,Arial,sans-serif;background:#050810;color:#e8ecf4;margin:0;padding:0}.card{background:#0d1526;border:1px solid #1d2535;border-radius:12px;padding:24px;margin:16px 0}.stat{display:inline-block;margin:8px 16px 8px 0}.stat-val{font-size:2rem;font-weight:900;font-family:monospace}.stat-label{font-size:0.72rem;color:#6b7a94;text-transform:uppercase;letter-spacing:1px}</style></head>
<body style="padding:32px">
  <div style="max-width:640px;margin:0 auto">
    <h1 style="color:#4f8fff;font-size:1.4rem">🛡 Watchtower Security Report</h1>
    <p style="color:#6b7a94">Client: <strong style="color:#e8ecf4">${body.clientName}</strong> · ${new Date().toLocaleDateString('en-GB', { year:'numeric', month:'long', day:'numeric' })}</p>
    ${summary ? `
    <div class="card">
      <h2 style="color:#22d49a;font-size:0.9rem;margin-bottom:16px">Executive Summary</h2>
      <div class="stat"><div class="stat-val" style="color:#f0405e">${summary.critAlerts || 0}</div><div class="stat-label">Critical Alerts</div></div>
      <div class="stat"><div class="stat-val" style="color:#22d49a">${summary.fpsClosed || 0}</div><div class="stat-label">FPs Auto-Resolved</div></div>
      <div class="stat"><div class="stat-val" style="color:#4f8fff">${summary.posture || 0}%</div><div class="stat-label">Posture Score</div></div>
      <div class="stat"><div class="stat-val" style="color:#f0a030">${summary.openCases || 0}</div><div class="stat-label">Open Cases</div></div>
      ${summary.narrative ? `<p style="margin-top:16px;color:#96a6bc;line-height:1.7">${summary.narrative}</p>` : ''}
    </div>` : `
    <div class="card">
      <p style="color:#6b7a94">No recent security data available. Connect your tools in the Watchtower dashboard to start receiving reports.</p>
    </div>`}
    <p style="font-size:0.72rem;color:#3d4d66;margin-top:32px">Generated by Watchtower · getwatchtower.io · ${new Date().toISOString()}</p>
  </div>
</body>
</html>`;

    const emailResult = await sendEmail({
      to: body.recipientEmail,
      subject: `Watchtower Security Report — ${body.clientName} — ${new Date().toLocaleDateString('en-GB')}`,
      html,
    });

    return NextResponse.json({ ok: true, sent: emailResult.ok, recipient: body.recipientEmail });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: e.message }, { status: 500 });
  }
}
